In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences.
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am a good boy',
        'i am a good interview',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good interview',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size.

voc_size = 10000

In [5]:
## One Hot Representation

one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[159, 9469, 8344, 7105],
 [159, 9469, 8344, 3610],
 [159, 308, 8344, 9168],
 [5079, 8284, 5990, 2277, 7435],
 [5079, 8284, 5990, 2277, 3738],
 [4852, 159, 2476, 8344, 1392],
 [51, 4584, 6207, 2277]]

In [6]:
## To see index of 'glass' in vocabulary.

one_hot('glass',voc_size)

[9469]

In [7]:
## Word Embedding Representation.

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import pandas  as pd
import numpy as np

In [9]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[   0    0    0    0  159 9469 8344 7105]
 [   0    0    0    0  159 9469 8344 3610]
 [   0    0    0    0  159  308 8344 9168]
 [   0    0    0 5079 8284 5990 2277 7435]
 [   0    0    0 5079 8284 5990 2277 3738]
 [   0    0    0 4852  159 2476 8344 1392]
 [   0    0    0    0   51 4584 6207 2277]]


In [10]:
## Feature representation..

dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embeded_docs)

1/1 [==============================] - 1s 578ms/step


array([[[-0.04710129,  0.03620065, -0.0278469 , -0.04429885,
          0.0082067 ,  0.02803427,  0.00564752, -0.02310201,
         -0.0025723 , -0.03468137],
        [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,
          0.0082067 ,  0.02803427,  0.00564752, -0.02310201,
         -0.0025723 , -0.03468137],
        [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,
          0.0082067 ,  0.02803427,  0.00564752, -0.02310201,
         -0.0025723 , -0.03468137],
        [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,
          0.0082067 ,  0.02803427,  0.00564752, -0.02310201,
         -0.0025723 , -0.03468137],
        [-0.02559054,  0.0010379 , -0.00203985, -0.00626668,
          0.00358626,  0.035189  ,  0.04408845, -0.03850945,
          0.0299433 , -0.02185397],
        [ 0.02554836,  0.00157478,  0.01806417,  0.03977901,
         -0.00447597,  0.03202567, -0.04774572, -0.02553369,
         -0.01068477, -0.04256615],
        [-0.03677461, -0.03337146,  0.01292341,  0.0

In [14]:
embeded_docs[0]

array([   0,    0,    0,    0,  159, 9469, 8344, 7105])

In [15]:
model.predict(embeded_docs[0])

1/1 [==============================] - 0s 107ms/step


array([[-0.04710129,  0.03620065, -0.0278469 , -0.04429885,  0.0082067 ,
         0.02803427,  0.00564752, -0.02310201, -0.0025723 , -0.03468137],
       [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,  0.0082067 ,
         0.02803427,  0.00564752, -0.02310201, -0.0025723 , -0.03468137],
       [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,  0.0082067 ,
         0.02803427,  0.00564752, -0.02310201, -0.0025723 , -0.03468137],
       [-0.04710129,  0.03620065, -0.0278469 , -0.04429885,  0.0082067 ,
         0.02803427,  0.00564752, -0.02310201, -0.0025723 , -0.03468137],
       [-0.02559054,  0.0010379 , -0.00203985, -0.00626668,  0.00358626,
         0.035189  ,  0.04408845, -0.03850945,  0.0299433 , -0.02185397],
       [ 0.02554836,  0.00157478,  0.01806417,  0.03977901, -0.00447597,
         0.03202567, -0.04774572, -0.02553369, -0.01068477, -0.04256615],
       [-0.03677461, -0.03337146,  0.01292341,  0.04561241,  0.04770649,
        -0.01844116,  0.04075236,  0.04460216